In [46]:
import numpy as np
import pandas as pd

In [47]:
z = np.array([[1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 10, 11, 12]])
z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
df=pd.read_csv('web scraped table.csv')
df

Unnamed: 0 Age group     IFR
0           1      0–34  0.004%
1           2     35–44  0.068%
2           3     45–54   0.23%
3           4     55–64   0.75%
4           5     65–74    2.5%
5           6     75–84    8.5%
6           7      85 +   28.3%

In [49]:
z.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [50]:
z.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [51]:
ar1=np.arange(10)
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
ar1=np.arange(0,10)
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
ar1=np.arange(0,10,2)
ar1

array([0, 2, 4, 6, 8])

In [54]:
ar1=np.zeros(5)
ar1

array([0., 0., 0., 0., 0.])

In [57]:
ar1=np.zeros((2,5))
ar1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [60]:
ar1=np.full((5),7)
ar1

array([7, 7, 7, 7, 7])

In [61]:
np.full((2,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [55]:
ar1=np.eye(2,2)
ar1

array([[1., 0.],
       [0., 1.]])

## convert python list to numpy array

In [72]:
list=[i for i in range(7)]
print(list)
print(type(list))
ar1=np.array(list)
print(ar1)
print(type(ar1))

[0, 1, 2, 3, 4, 5, 6]
<class 'list'>
[0 1 2 3 4 5 6]
<class 'numpy.ndarray'>


# Slicing numpy arrays

In [91]:
ar1=np.array([i for i in range(10)])
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
print('ar1 array:',ar1[1:5])
print()
ar2=ar1.reshape(2,5)
print('reshaped ar1 array:',ar2)
print()
print(f'second column:{ar2[:,1]}')    # f string
print()
print(ar1[1:5:2])

ar1 array: [1 2 3 4]

reshaped ar1 array: [[0 1 2 3 4]
 [5 6 7 8 9]]

second column:[1 6]

[1 3]


In [110]:
print(ar1)
ar1_sqr=np.sqrt(ar1)
print()
print(ar1_sqr)
print()
print(np.arange(-5,9))
print()
print(np.absolute(np.arange(-5,9)))
print(np.exp(ar1))
print()

[0 1 2 3 4 5 6 7 8 9]

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]

[-5 -4 -3 -2 -1  0  1  2  3  4  5  6  7  8]

[5 4 3 2 1 0 1 2 3 4 5 6 7 8]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]



# Copy vs View numpy

### both are copy of array but view is connected to the original

In [111]:
np1=np.array([i for i in range(10)])
np1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
np2=np1.view()
np2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
np2[1]=40
print(np1)
print()
print(np2)

[ 0 40  2  3  4  5  6  7  8  9]

[ 0 40  2  3  4  5  6  7  8  9]


In [121]:
np3=np1.copy()
print("original np1",np3)
np3[1]=70
print("after making changes in np3")
print("original np1", np1)
print("changed np3:",np3)

original np1 [ 0 40  2  3  4  5  6  7  8  9]
after making changes in np3
original np1 [ 0 40  2  3  4  5  6  7  8  9]
changed np3: [ 0 70  2  3  4  5  6  7  8  9]


# Reshape for flatten to 1-D

In [129]:
np1=np.array([[1,2,3],[4,5,6]])
print(f"original array {np1}")
np2=np1.reshape(-1)
print()
print(f"flatten array {np2}")

original array [[1 2 3]
 [4 5 6]]

flatten array [1 2 3 4 5 6]


In [134]:
np1=np.array([4,2,6,8,23,5])
print(f"original array:{np1}")
print()
print(f"sorted array: {np.sort(np1)}")

original array:[ 4  2  6  8 23  5]

sorted array: [ 2  4  5  6  8 23]


In [138]:
np1=np.array(["True","False","True","False"])
print(f"original array: {np1}")
print()
print(f"sorted array: {np.sort(np1)}")  # False act like 0 and True act like 1

original array: ['True' 'False' 'True' 'False']

sorted array: ['False' 'False' 'True' 'True']


In [141]:
np1=np.array([i for i in range(10)])
print(f"original array:{np1}")

original array:[0 1 2 3 4 5 6 7 8 9]


In [150]:
x=np.where(np1==3)
print(x)
y=np.where(np1%2==0)
print(f"array of index with even numbers: {y}")

(array([3], dtype=int64),)
array of index with even numbers: (array([0, 2, 4, 6, 8], dtype=int64),)


In [153]:
print(np1)
filtered=np1%2==0
print(filtered)
print()
print(np1[filtered])

[0 1 2 3 4 5 6 7 8 9]
[ True False  True False  True False  True False  True False]

[0 2 4 6 8]
