In [48]:
import random
import numpy as np

In [17]:
a=random.randint(5,10)    # return a value b/w 5 and 10 including both values
a

7

In [25]:
a=random.randrange(3,9)  # return a value b/w 3 and 9 where 3(included) and 9(not included)
a

3

In [28]:
l=['apple','banana','cherry']
a=random.choice(l)
print(a)

apple


In [31]:
a=random.random()  # return a float number b/w 0 and 1
a

0.4282852972448553

In [39]:
a=random.uniform(1,10)  # return a float number b/w 2 given number
a

5.889031904434809

In [46]:
l=[1,2,7,4,5]
random.shuffle(l)
print(f'after shuffling values : {l}')
print()
l=['apple','banana','cherry','grapes']
random.shuffle(l)
print(f'after shuffling values : {l}')

after shuffling values : [1, 7, 4, 5, 2]

after shuffling values : ['banana', 'cherry', 'grapes', 'apple']


# Random with numpy

In [63]:
a=np.random.rand()  # return a number b/w 0 and 1
a

0.5747609533153908

In [59]:
a=np.random.randn()    # return a number close to 0 +ve and -ve both
print(a)
print(type(a))

-0.033158857757929885
<class 'float'>


In [65]:
a=np.random.randn(2)    # will return an array of given size with values close to 0
a

array([0.44486299, 0.21186527])

In [70]:
a=np.random.ranf((3,3))   # return an array of given shape and float values in half open [0,1)
a

array([[0.09049989, 0.75777227, 0.61938662],
       [0.10763   , 0.9038291 , 0.27015124],
       [0.14170863, 0.01479876, 0.63473849]])

In [78]:
a=np.random.randint(2,10)  # return a random value from given range
a

5

In [94]:
a=np.random.random_sample((5,3))
a

array([[0.855331  , 0.2306268 , 0.37812512],
       [0.63959534, 0.98879381, 0.77043582],
       [0.48467567, 0.79188548, 0.49798605],
       [0.30038231, 0.0713177 , 0.64362089],
       [0.12757007, 0.32925006, 0.03537926]])

In [96]:
# help(np.random.random_sample)